export const mockWeeklyReportData = {
  thisWeek: {
    stats: {
      customers: 10,
      totalProducts: 6,
      stockProducts: 5,
      outOfStock: 1,
      revenue: 3492.4,
    },
    chartData: {
      customers: [
        { day: "Sun", value: 10 },
        { day: "Mon", value: 10 },
        { day: "Tue", value: 10 },
        { day: "Wed", value: 10 },
        { day: "Thu", value: 10 },
        { day: "Fri", value: 10 },
        { day: "Sat", value: 10 },
      ],
      totalProducts: [
        { day: "Sun", value: 6 },
        { day: "Mon", value: 6 },
        { day: "Tue", value: 6 },
        { day: "Wed", value: 6 },
        { day: "Thu", value: 6 },
        { day: "Fri", value: 6 },
        { day: "Sat", value: 6 },
      ],
      stockProducts: [
        { day: "Sun", value: 5 },
        { day: "Mon", value: 5 },
        { day: "Tue", value: 5 },
        { day: "Wed", value: 5 },
        { day: "Thu", value: 5 },
        { day: "Fri", value: 5 },
        { day: "Sat", value: 5 },
      ],
      outOfStock: [
        { day: "Sun", value: 1 },
        { day: "Mon", value: 1 },
        { day: "Tue", value: 1 },
        { day: "Wed", value: 1 },
        { day: "Thu", value: 1 },
        { day: "Fri", value: 1 },
        { day: "Sat", value: 1 },
      ],
      revenue: [
        { day: "Sun", value: 450 },
        { day: "Mon", value: 520 },
        { day: "Tue", value: 480 },
        { day: "Wed", value: 610 },
        { day: "Thu", value: 550 },
        { day: "Fri", value: 490 },
        { day: "Sat", value: 392 },
      ],
    },
  },
  lastWeek: {
    stats: {
      customers: 8,
      totalProducts: 5,
      stockProducts: 4,
      outOfStock: 1,
      revenue: 2850.0,
    },
    chartData: {
      customers: [
        { day: "Sun", value: 8 },
        { day: "Mon", value: 8 },
        { day: "Tue", value: 8 },
        { day: "Wed", value: 8 },
        { day: "Thu", value: 8 },
        { day: "Fri", value: 8 },
        { day: "Sat", value: 8 },
      ],
      totalProducts: [
        { day: "Sun", value: 5 },
        { day: "Mon", value: 5 },
        { day: "Tue", value: 5 },
        { day: "Wed", value: 5 },
        { day: "Thu", value: 5 },
        { day: "Fri", value: 5 },
        { day: "Sat", value: 5 },
      ],
      stockProducts: [
        { day: "Sun", value: 4 },
        { day: "Mon", value: 4 },
        { day: "Tue", value: 4 },
        { day: "Wed", value: 4 },
        { day: "Thu", value: 4 },
        { day: "Fri", value: 4 },
        { day: "Sat", value: 4 },
      ],
      outOfStock: [
        { day: "Sun", value: 1 },
        { day: "Mon", value: 1 },
        { day: "Tue", value: 1 },
        { day: "Wed", value: 1 },
        { day: "Thu", value: 1 },
        { day: "Fri", value: 1 },
        { day: "Sat", value: 1 },
      ],
      revenue: [
        { day: "Sun", value: 380 },
        { day: "Mon", value: 410 },
        { day: "Tue", value: 390 },
        { day: "Wed", value: 450 },
        { day: "Thu", value: 420 },
        { day: "Fri", value: 400 },
        { day: "Sat", value: 400 },
      ],
    },
  },
};

export const mockCustomerOverviewData = {
  thisWeek: {
    stats: {
      activeCustomers: 10,
      repeatCustomers: 0,
      shopVisitor: 0,
      conversionRate: "0%",
    },
    chartData: {
      activeCustomers: [
        { day: "Sun", value: 10 },
        { day: "Mon", value: 10 },
        { day: "Tue", value: 10 },
        { day: "Wed", value: 10 },
        { day: "Thu", value: 10 },
        { day: "Fri", value: 10 },
        { day: "Sat", value: 10 },
      ],
      repeatCustomers: [
        { day: "Sun", value: 0 },
        { day: "Mon", value: 0 },
        { day: "Tue", value: 0 },
        { day: "Wed", value: 0 },
        { day: "Thu", value: 0 },
        { day: "Fri", value: 0 },
        { day: "Sat", value: 0 },
      ],
      shopVisitor: [
        { day: "Sun", value: 0 },
        { day: "Mon", value: 0 },
        { day: "Tue", value: 0 },
        { day: "Wed", value: 0 },
        { day: "Thu", value: 0 },
        { day: "Fri", value: 0 },
        { day: "Sat", value: 0 },
      ],
      conversionRate: [
        { day: "Sun", value: 0 },
        { day: "Mon", value: 0 },
        { day: "Tue", value: 0 },
        { day: "Wed", value: 0 },
        { day: "Thu", value: 0 },
        { day: "Fri", value: 0 },
        { day: "Sat", value: 0 },
      ],
    },
  },
  lastWeek: {
    stats: {
      activeCustomers: 8,
      repeatCustomers: 0,
      shopVisitor: 0,
      conversionRate: "0%",
    },
    chartData: {
      activeCustomers: [
        { day: "Sun", value: 8 },
        { day: "Mon", value: 8 },
        { day: "Tue", value: 8 },
        { day: "Wed", value: 8 },
        { day: "Thu", value: 8 },
        { day: "Fri", value: 8 },
        { day: "Sat", value: 8 },
      ],
      repeatCustomers: [
        { day: "Sun", value: 0 },
        { day: "Mon", value: 0 },
        { day: "Tue", value: 0 },
        { day: "Wed", value: 0 },
        { day: "Thu", value: 0 },
        { day: "Fri", value: 0 },
        { day: "Sat", value: 0 },
      ],
      shopVisitor: [
        { day: "Sun", value: 0 },
        { day: "Mon", value: 0 },
        { day: "Tue", value: 0 },
        { day: "Wed", value: 0 },
        { day: "Thu", value: 0 },
        { day: "Fri", value: 0 },
        { day: "Sat", value: 0 },
      ],
      conversionRate: [
        { day: "Sun", value: 0 },
        { day: "Mon", value: 0 },
        { day: "Tue", value: 0 },
        { day: "Wed", value: 0 },
        { day: "Thu", value: 0 },
        { day: "Fri", value: 0 },
        { day: "Sat", value: 0 },
      ],
    },
  },
};
